repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args:
          [
            "--strict",
            "--ignore-missing-imports",
            "--config-file=./backend/pyproject.toml",
            "backend/src",
          ]
