[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Connor", email = "11376396+Viibrant@users.noreply.github.com" },
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
 "mcp[cli]>=1.4.1",
 "numpy>=2.2.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[dependency-groups]
dev = ["pytest>=8.3.5"]
