name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.12-bookworm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/pyproject.toml', 'backend/uv.lock') }}
      - name: Install deps
        working-directory: backend
        run: uv sync --all-extras --dev
      - name: Run tests
        working-directory: backend
        run: uv run pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1
      - name: Install deps
        working-directory: frontend
        run: bun install --frozen-lockfile
      - name: Lint + typecheck
        working-directory: frontend
        run: bun run lint && bun run tsc --noEmit
      - name: Build
        working-directory: frontend
        run: bun run build

  docker-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build images
        run: make build-all
